name: First steps with Action

on:
    push:
        branches: main

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Check Actions
              uses: actions/checkou@v4

            - name: Hello Dev
              run: |
                echo ola mundo
    
    second-job:
        runs-on: ubuntu-latest
        steps:
            - name: Check Actions
              uses: actions/checkout@v4

            - name: Completing second job
              run: |
                echo exiting from action

